# Generated by Django 3.0.5 on 2020-04-04 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ca', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('cases', models.IntegerField(default=None)),
                ('deceases', models.IntegerField(default=None)),
                ('cured', models.IntegerField(default=None)),
                ('hospitalized', models.IntegerField(default=None)),
                ('uci', models.IntegerField(default=None)),
                ('accIncidence', models.IntegerField(default=None)),
                ('diffCases', models.IntegerField(default=None)),
            ],
        ),
    ]
