# Generated by Django 3.0.5 on 2020-04-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='accIncidence',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='report',
            name='cases',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='report',
            name='cured',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='report',
            name='deceases',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='report',
            name='diffCases',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='report',
            name='hospitalized',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='report',
            name='uci',
            field=models.IntegerField(default=-1),
        ),
    ]
