# Generated by Django 3.0.5 on 2020-04-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20200404_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='cases',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
